# .github/workflows/release.yml

name: Build and Deploy

on:
  release:
    types: [published]

env:
  NODE_VERSION: 18

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: check theme version against tag
        run: |
          THEME_VERSION=$(cat sass/style.scss | grep Version | sed -r 's/version: +//I')
          V="v"
          echo Version in style.scss: $THEME_VERSION

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install npm packages
        run: npm ci

      - name: Build CSS
        run: npm run compile:build

      - name: Build CSS-RTL
        run: npm run compile:rtl

      - name: Build JS
        run: npm run build

      - name: run install composer
        run: composer install

      - name: Make bundle
        run: npm run bundle

  build-zip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: fail on fork
          if: github.repository_owner != 'verdigado'
          run: exit 1

      - name: Echo debug
        run: |
          echo "sunflower-${{ github.ref_name }}.zip"
          ls -la

      - name: Install Dependencies
        run: npm ci

      - name: Make bundle
        run: npm run bundle

      - name: Rename ZIP file
        run: |
          mv ../sunflower.zip sunflower-${{ github.ref_name }}.zip

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "sunflower-${{ github.ref_name }}.zip"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-zip
    steps:
      - uses: actions/checkout@v4

      - name: Provide deploy_key
        env:
          DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir "$HOME/.ssh"
          echo "$DEPLOY_KEY" > "$HOME/.ssh/id_rsa"
          file "$HOME/.ssh/id_rsa"
          chmod 600 "$HOME/.ssh/id_rsa"

      - name: save version
        run: echo ${GITHUB_REF##*/} > version.txt

      - name: rsync zipfile, version and changelog
        run: rsync -z -e "ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/id_rsa" ../sunflower-${{ github.ref_name }}.zip version.txt github-ci@wordpress05.gcms.verdigado.net:/var/www/updateserver/
