name: CI

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: provide deploy_key
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          mkdir "$HOME/.ssh"
          echo "$DEPLOY_KEY" > "$HOME/.ssh/id_rsa"
          chmod 600 "$HOME/.ssh/id_rsa"
      - name: test ssh
        run: ssh -v -o StrictHostKeyChecking=no -i $HOME/.ssh/id_rsa tom@sharepicgenerator.de pwd
      - name: rsync
        run: rsync -avhz -e "ssh -v -o StrictHostKeyChecking=no -i $HOME/.ssh/id_rsa" 404.php tom@sharepicgenerator.de:/var/www/wordpress.tom-rose.de/updateserver/


      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install npm packages
        run: npm install
      - name: Build scss
        run: npm run compile:build
      - name: Make bundle
        run: npm run bundle

      - name: provide deploy_key
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          mkdir "$HOME/.ssh"
          echo "$DEPLOY_KEY" > "$HOME/.ssh/id_rsa"
          chmod 600 "$HOME/.ssh/id_rsa"
      - name: rsync
        run: rsync -avhz -e "ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/id_rsa" ../sunflower.zip sharepicgenerator.de:/var/www/wordpress.tom-rose.de/updateserver/

